export const STUDIES={
  CL04041383:{code:'CL04041383',name:'Olokizumab OLE',subtitle:'Visits · regimens · monitoring',modules:['overview','patients','actions','reports','data','ai'],labelProtocol:null},
  CL04041109:{code:'CL04041109',name:'Medication Labels',subtitle:'Medication / placebo label workflow',modules:['labels','data','ai'],labelProtocol:'CL04041109'}
};

export const VISITS=[
  [1,0,0,'Screening / Visit 1 (Days - 14 - 0)'],[2,2,14,'Visit 2 / Week 2 (Day 14)'],[3,6,42,'Visit 3 / Week 6 (Day 42)'],
  [4,10,70,'Visit 4 / Week 10 (Day 70)'],[5,16,112,'Visit 5 / Week 16 (Day 112)'],[6,22,154,'Visit 6 / Week 22 (Day 154)'],
  [7,28,196,'Visit 7 / Week 28 (Day 196)'],[8,34,238,'Visit 8 / Week 34 (Day 238)'],[9,40,280,'Visit 9 / Week 40 (Day 280)'],
  [10,46,322,'Visit 10 / Week 46 (Day 322)'],[11,54,378,'Visit 11 / Week 54 (Day 378)']
];
export const BASELINE={'10-01':2,'10-04':2,'10-05':2,'10-10':4,'10-11':4,'10-12':4,'10-13':4,'10-14':2,'10-15':4,'10-17':4,'10-18':4,'10-19':2,'10-20':2,'10-21':4,'10-22':4};
export const REGCOL={1:['V0_DISP_REGIMEN','V0_DISP_REGIMEN1'],2:['V2_DISP_REGIMEN','V2_DISP_REGIMEN1'],3:['V3_DISP_REGIMEN','V3_DISP_REGIMEN1'],4:['V4_DISP_REGIMEN','V4_DISP_REGIMEN1'],5:['V5_DISP_REGIMEN','V5_DISP_REGIMEN1'],6:['V6_DISP_REGIMEN','V6_DISP_REGIMEN1'],7:['V7_DISP_REGIMEN','V7_DISP_REGIMEN1'],8:['V8_DISP_REGIMEN','V8_DISP_REGIMEN1'],9:['V9_DISP_REGIMEN','V9_DISP_REGIMEN1'],10:['V10_DISP_REGIMEN','V10_DISP_REGIMEN1'],11:['V11_DISP_REGIMEN','V11_DISP_REGIMEN1']};

export function normalizeSite(value){const s=String(value??'').trim();if(!s)return'';return /^\d+\.0+$/.test(s)?String(parseInt(s,10)):s;}
export function inferSiteFromId(value){const s=String(value??'').trim();const m=s.match(/^([A-Za-z0-9]+)-/);return m?normalizeSite(m[1]):'';}
export function rowSite(row){const direct=normalizeSite(row?.['Site #']??row?.['Site']??row?.['Site No']??row?.['Site Number']);return direct||inferSiteFromId(row?.['Столбец1']??row?.['Screening #']??row?.['Randomization #']);}
export function selectPatientId(row){return String(row?.['Столбец1']??row?.['Screening #']??row?.['Randomization #']??'').trim();}
export function visitPatientId(row){return String(row?.['Screening #']??row?.['Randomization #']??row?.['Столбец1']??'').trim();}
export function discoverSites(selectRows=[],visitRows=[]){const found=new Set();[...selectRows,...visitRows].forEach(r=>{const s=rowSite(r);if(s)found.add(s);});return [...found].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'}));}
export function cleanDate(v){if(!v)return null;const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?null:d;}
function regimen(row,no){const [a,b]=REGCOL[no];return String(row?.[b]||row?.[a]||'').trim();}

export function buildPatients(site,selectRows=[],visitRows=[],noteFor=()=>({})){const s=String(site||'');if(!s)return[];const select=selectRows.filter(r=>rowSite(r)===s),visitsForSite=visitRows.filter(r=>rowSite(r)===s),byPatient=new Map();select.forEach(r=>{const id=selectPatientId(r);if(id)byPatient.set(id,r);});visitsForSite.forEach(r=>{const id=visitPatientId(r);if(id&&!byPatient.has(id))byPatient.set(id,{});});const visitMap=new Map();visitsForSite.forEach(r=>{const id=visitPatientId(r),activity=String(r.Activity||'').trim();if(id&&activity)visitMap.set(`${id}|${activity}`,r);});return [...byPatient].map(([id,row])=>{let prev='';const visits=VISITS.map(([no,week,day,activity])=>{const vr=visitMap.get(`${id}|${activity}`)||{};let rg=regimen(row,no);const n=noteFor(id,no)||{};if(n.overrideRegimen)rg=n.overrideRegimen;const actual=cleanDate(n.overrideDate||vr['Actual visit date']),min=cleanDate(vr['Scheduled min']),max=cleanDate(vr['Scheduled max']);let window='Pending';if(actual&&min&&max)window=actual<min?'Early':actual>max?'Late':'Within';const before=prev||rg,changed=Boolean((no===6||no===9)&&prev&&rg&&prev!==rg);if(rg)prev=rg;return {no,week,day,activity,actual,min,max,window,regimen:rg,before,changed};});return {id,baseline:BASELINE[id]??'—',status:String(row['Status']||'Unknown'),visits,violations:visits.filter(v=>v.window==='Early'||v.window==='Late').length};}).sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true,sensitivity:'base'}));}

export function visitDueState(v,now=new Date()){if(v.actual||!v.min||!v.max)return null;const day=86400000,today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),min=new Date(v.min.getFullYear(),v.min.getMonth(),v.min.getDate()),max=new Date(v.max.getFullYear(),v.max.getMonth(),v.max.getDate()),toMin=Math.ceil((min-today)/day),toMax=Math.ceil((max-today)/day);if(toMax<0)return {kind:'overdue',days:Math.abs(toMax),label:`Overdue ${Math.abs(toMax)}d`};if(toMax<=7)return {kind:'due',days:toMax,label:toMax===0?'Window closes today':`Window closes in ${toMax}d`};if(toMin<=14&&toMin>=0)return {kind:'upcoming',days:toMin,label:toMin===0?'Window opens today':`Window opens in ${toMin}d`};return null;}

export function summarizeSite(site,selectRows,visitRows,noteFor,now=new Date()){const patients=buildPatients(site,selectRows,visitRows,noteFor),events=[];let changes=0;patients.forEach(p=>p.visits.forEach(v=>{if(v.changed)changes++;const due=visitDueState(v,now);if(due)events.push({patient:p.id,visit:v.no,week:v.week,...due,min:v.min,max:v.max});}));return {site,patients:patients.length,exceptions:patients.reduce((a,p)=>a+p.violations,0),regimenChanges:changes,dueSoon:events.filter(x=>x.kind==='due').length,overdue:events.filter(x=>x.kind==='overdue').length,upcoming:events.filter(x=>x.kind==='upcoming').length,events,patientRows:patients};}
export function summarizeAllSites(sites,selectRows,visitRows,noteFor,now=new Date()){return sites.map(site=>summarizeSite(site,selectRows,visitRows,(p,v)=>noteFor(site,p,v),now));}

export function classifyImport(rows=[]){const columns=Object.keys(rows[0]||{});if(columns.includes('Activity')&&(columns.includes('Actual visit date')||columns.includes('Scheduled min')))return 'visits';if(columns.includes('Randomization #')||columns.some(n=>String(n).includes('DISP_REGIMEN')))return 'select';return 'unknown';}
export function analyzeImport(name,rows=[]){const kind=classifyImport(rows),columns=Object.keys(rows[0]||{}),sites=discoverSites(kind==='select'?rows:[],kind==='visits'?rows:[]),subjects=new Set();rows.forEach(r=>{const id=kind==='visits'?visitPatientId(r):selectPatientId(r);if(id)subjects.add(id);});const warnings=[];if(!rows.length)warnings.push('No data rows found');if(kind==='unknown')warnings.push('Source type was not recognized automatically');if(!sites.length&&kind!=='unknown')warnings.push('No Site # values were recognized');if(kind==='visits'&&!columns.includes('Actual visit date'))warnings.push('Actual visit date column is missing');return {id:`imp_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,name,kind,rows,columns,sites,subjects:subjects.size,warnings};}
