import JSZip from 'jszip';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
const PROTOCOL='CL04041109',PRODUCT='Placebo',FOOTER='Только для клинических исследований';
const norm=s=>String(s??'').replace(/\s+/g,' ').trim(),uniq=a=>[...new Set(a.map(norm).filter(Boolean))],xmlEscape=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[m])),safeName=s=>String(s||'labels').replace(/[^a-z0-9._-]+/gi,'_');
function candidateHeaderIndex(headers){const patterns=[/kit\s*(label|number|no|id)/i,/(individual|randomization)\s*(number|no|id)/i,/label\s*(number|no|id)?/i,/(номер|код).*(набора|этикетки|индивидуаль)/i];for(const p of patterns){const i=headers.findIndex(h=>p.test(norm(h)));if(i>=0)return i;}return-1;}
function plausibleToken(v){const s=norm(v);if(!s||s.length>32||/\s/.test(s)||/^\d{1,2}[./-]\d{1,2}[./-]\d{2,4}$/.test(s)||/^CL\d{6,}$/i.test(s)||/^(placebo|batch|manufactured|manufacturing|expiry|exp|mfg|subcutaneous|protocol|visit|site)$/i.test(s)||!/^[A-Za-zА-Яа-я0-9_-]+$/.test(s))return false;return /\d/.test(s);}
function extractFromRows(rows){if(!rows.length)return[];const headers=Object.keys(rows[0]||{}),idx=candidateHeaderIndex(headers);if(idx>=0){const key=headers[idx];return uniq(rows.map(r=>r[key]).filter(v=>norm(v)));}const candidates=[];for(const r of rows)for(const v of Object.values(r))if(plausibleToken(v))candidates.push(norm(v));const counts=new Map();candidates.forEach(x=>counts.set(x,(counts.get(x)||0)+1));return uniq(candidates.filter(x=>(counts.get(x)||0)<=3));}
async function importExcel(file){const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:false}),ids=[];for(const sheetName of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{defval:''});ids.push(...extractFromRows(rows));}return uniq(ids);}
function textOf(node){return [...node.getElementsByTagNameNS('*','t')].map(x=>x.textContent||'').join('').trim();}
async function importDocx(file){const zip=await JSZip.loadAsync(await file.arrayBuffer()),xmlFile=zip.file('word/document.xml');if(!xmlFile)throw new Error('This Word file does not contain word/document.xml');const xml=await xmlFile.async('text'),doc=new DOMParser().parseFromString(xml,'application/xml'),tableRows=[...doc.getElementsByTagNameNS('*','tr')].map(tr=>[...tr.getElementsByTagNameNS('*','tc')].map(textOf));if(tableRows.length){const headers=tableRows[0]||[],idx=candidateHeaderIndex(headers);if(idx>=0)return uniq(tableRows.slice(1).map(r=>r[idx]).filter(Boolean));}const chunks=[];[...doc.getElementsByTagNameNS('*','p')].forEach(p=>{const t=textOf(p);if(t)chunks.push(t);});tableRows.flat().forEach(t=>{if(t)chunks.push(t);});const candidates=chunks.flatMap(t=>t.split(/[\s,;|]+/)).map(norm).filter(plausibleToken),counts=new Map();candidates.forEach(x=>counts.set(x,(counts.get(x)||0)+1));return uniq(candidates.filter(x=>(counts.get(x)||0)<=3));}
export async function importLabelFile(file){const name=String(file?.name||'').toLowerCase();let ids=[];if(name.endsWith('.xlsx')||name.endsWith('.xls'))ids=await importExcel(file);else if(name.endsWith('.docx'))ids=await importDocx(file);else throw new Error('Supported label imports: .xlsx, .xls and .docx');return {ids:uniq(ids),source:file.name};}
function settings(job){let width=40,height=20,perLabel=1;if(job.layout==='80x60'){width=80;height=60;perLabel=10;}else if(job.layout==='custom'){width=Math.max(20,Math.min(150,Number(job.width)||40));height=Math.max(15,Math.min(100,Number(job.height)||20));perLabel=Math.max(1,Math.min(30,Number(job.perLabel)||1));}return {width,height,perLabel,copies:Math.max(1,Math.min(20,Number(job.copies)||1)),codeMode:['text','code128','qr'].includes(job.codeMode)?job.codeMode:'text'};}
function groupsFor(job){const s=settings(job),base=Array.from({length:Math.ceil(job.ids.length/s.perLabel)},(_,i)=>job.ids.slice(i*s.perLabel,i*s.perLabel+s.perLabel)),groups=[];base.forEach(g=>{for(let i=0;i<s.copies;i++)groups.push([...g]);});return {groups,...s};}
export function exportLabelExcel(job){if(!job.ids?.length)throw new Error('No label IDs loaded');const wb=XLSX.utils.book_new(),s=settings(job),aoa=[['Protocol','Product','Batch','Manufactured','Expiry','Width mm','Height mm','IDs per label','Copies','Code mode',...Array.from({length:s.perLabel},(_,i)=>`ID ${i+1}`)]];for(let i=0;i<job.ids.length;i+=s.perLabel)aoa.push([PROTOCOL,PRODUCT,job.batch,job.mfg,job.exp,s.width,s.height,s.perLabel,s.copies,s.codeMode,...job.ids.slice(i,i+s.perLabel)]);const ws=XLSX.utils.aoa_to_sheet(aoa);ws['!cols']=[{wch:15},{wch:12},{wch:12},{wch:14},{wch:14},{wch:10},{wch:10},{wch:12},{wch:8},{wch:10},...Array.from({length:s.perLabel},()=>({wch:14}))];XLSX.utils.book_append_sheet(wb,ws,'Labels');XLSX.writeFile(wb,`Clinical_Ops_Labels_${job.layout}.xlsx`);}
function wp(text,{bold=false,size=16,align='center'}={}){return `<w:p><w:pPr><w:jc w:val="${align}"/><w:spacing w:before="0" w:after="0" w:line="200" w:lineRule="auto"/></w:pPr><w:r><w:rPr>${bold?'<w:b/>':''}<w:sz w:val="${size}"/><w:szCs w:val="${size}"/></w:rPr><w:t xml:space="preserve">${xmlEscape(text)}</w:t></w:r></w:p>`;}
function tableXml(ids,cols=2){const rows=[];for(let i=0;i<ids.length;i+=cols)rows.push(`<w:tr>${ids.slice(i,i+cols).map(x=>`<w:tc><w:tcPr><w:tcW w:w="2100" w:type="dxa"/></w:tcPr>${wp(x,{bold:true,size:18})}</w:tc>`).join('')}</w:tr>`);return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr>${rows.join('')}</w:tbl>`;}
function wordPage(group,job){const s=settings(job),meta=`Batch ${job.batch} · Mfg ${job.mfg} · Exp ${job.exp}`;if(s.perLabel>1)return `${wp(`${PROTOCOL} · ${PRODUCT}`,{bold:true,size:20})}${wp(meta,{size:14})}${tableXml(group,s.perLabel>8?2:1)}${wp(FOOTER,{size:12})}`;return `${wp(`${PROTOCOL} · ${PRODUCT}`,{bold:true,size:16})}${wp(meta,{size:9})}${wp(group[0]||'',{bold:true,size:26})}${wp(FOOTER,{size:8})}`;}
export async function exportLabelWord(job){if(!job.ids?.length)throw new Error('No label IDs loaded');const zip=new JSZip(),{groups,width,height}=groupsFor(job),page={w:Math.round(width*56.6929),h:Math.round(height*56.6929),m:Math.max(40,Math.round(Math.min(width,height)*4))},body=groups.map((g,i)=>wordPage(g,job)+(i<groups.length-1?'<w:p><w:r><w:br w:type="page"/></w:r></w:p>':'')).join(''),documentXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="${page.w}" w:h="${page.h}"/><w:pgMar w:top="${page.m}" w:right="${page.m}" w:bottom="${page.m}" w:left="${page.m}" w:header="0" w:footer="0" w:gutter="0"/></w:sectPr></w:body></w:document>`;zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder('word').file('document.xml',documentXml);downloadBlob(await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),`Clinical_Ops_Labels_${job.layout}.docx`);}
function drawCanvas(group,job){const s=settings(job),scale=12,c=document.createElement('canvas');c.width=s.width*scale;c.height=s.height*scale;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#111';x.lineWidth=2;x.strokeRect(2,2,c.width-4,c.height-4);x.fillStyle='#111';x.textAlign='center';x.textBaseline='middle';const unit=Math.max(10,Math.min(c.width,c.height));x.font=`bold ${Math.max(13,Math.round(unit*.055))}px Arial`;x.fillText(`${PROTOCOL} · ${PRODUCT}`,c.width/2,Math.max(18,c.height*.09));x.font=`${Math.max(10,Math.round(unit*.032))}px Arial`;x.fillText(`Batch ${job.batch} · Mfg ${job.mfg} · Exp ${job.exp}`,c.width/2,Math.max(38,c.height*.16));const cols=group.length>4?2:1,rows=Math.ceil(group.length/cols),top=c.height*.26,bottom=c.height*.82,cellH=(bottom-top)/Math.max(1,rows);x.font=`bold ${Math.max(14,Math.round(unit*.07))}px Arial`;group.forEach((v,i)=>{const col=i%cols,row=Math.floor(i/cols);x.fillText(v,(col+.5)*c.width/cols,top+(row+.5)*cellH);});x.font=`${Math.max(9,Math.round(unit*.026))}px Arial`;x.fillText(FOOTER,c.width/2,c.height-14);return c;}
export function exportLabelPdf(job){if(!job.ids?.length)throw new Error('No label IDs loaded');const {groups,width,height}=groupsFor(job),orientation=width>=height?'landscape':'portrait',pdf=new jsPDF({orientation,unit:'mm',format:[width,height],compress:true});groups.forEach((g,i)=>{if(i)pdf.addPage([width,height],orientation);const canvas=drawCanvas(g,job);pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,width,height,undefined,'FAST');});pdf.save(`Clinical_Ops_Labels_${job.layout}.pdf`);}
function tscEscape(s){return String(s??'').replace(/"/g,"'").replace(/[\r\n]+/g,' ');}
export function exportLabelTsc(job){if(!job.ids?.length)throw new Error('No label IDs loaded');const {groups,width,height,codeMode}=groupsFor(job),docs=[];for(const group of groups){const lines=[`SIZE ${width} mm,${height} mm`,'GAP 2 mm,0 mm','DIRECTION 1','CLS',`TEXT 20,18,"0",0,1,1,"${tscEscape(PROTOCOL+' · '+PRODUCT)}"`,`TEXT 20,44,"0",0,1,1,"${tscEscape('Batch '+job.batch+' · '+job.exp)}"`];group.forEach((id,i)=>{const y=80+i*45;if(codeMode==='qr')lines.push(`QRCODE 20,${y},L,4,A,0,"${tscEscape(id)}"`);else if(codeMode==='code128')lines.push(`BARCODE 20,${y},"128",45,1,0,2,2,"${tscEscape(id)}"`);else lines.push(`TEXT 20,${y},"0",0,2,2,"${tscEscape(id)}"`);});lines.push(`TEXT 20,${Math.max(100,Math.round(height*8.5))},"0",0,1,1,"${tscEscape(FOOTER)}"`,'PRINT 1');docs.push(lines.join('\n'));}downloadBlob(new Blob([docs.join('\n\n')],{type:'text/plain;charset=utf-8'}),`Clinical_Ops_Labels_${job.layout}.tspl`);}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=safeName(name);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
